# Generated by Django 5.2.3 on 2025-07-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default="M",
                max_length=1,
            ),
        ),
    ]
