# Generated by Django 5.2.3 on 2025-07-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_calendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
